import express from 'express';
import { requireAuth, requirePermission } from '../middleware/auth.js';
import { validate } from '../lib/validate.js';
import { ApiError } from '../lib/errors.js';
import prisma from '../lib/prisma.js';
import { createMaintenanceSchema, updateMaintenanceSchema } from '../schemas/maintenance.js';
import logger from '../lib/logger.js';

const router = express.Router();

// All routes require authentication
router.use(requireAuth);

// Valid state transitions
const STATE_TRANSITIONS = {
  open: ['assigned', 'cancelled'],
  assigned: ['in_progress', 'blocked', 'cancelled', 'open'],
  in_progress: ['blocked', 'resolved', 'cancelled'],
  blocked: ['in_progress', 'cancelled'],
  resolved: ['closed', 'in_progress'],
  closed: [],
  cancelled: [],
};

function validateStateTransition(from_status, to_status) {
  const allowed = STATE_TRANSITIONS[from_status] || [];
  return allowed.includes(to_status);
}

/**
 * POST /api/v1/maintenance
 * Create maintenance request with auto-routing
 */
router.post('/', requirePermission('maintenance.write'), validate(createMaintenanceSchema), async (req, res, next) => {
  try {
    const {
      camp_id,
      room_id,
      category_id,
      title,
      description,
      priority,
      reported_by_name,
      image_urls,
    } = req.body;

    // Verify camp belongs to tenant
    const camp = await prisma.camps.findFirst({
      where: { id: camp_id, tenant_id: req.tenantId },
    });

    if (!camp) {
      throw new ApiError('NOT_FOUND', 'Camp not found', 404);
    }

    // If room specified, verify it belongs to camp
    if (room_id) {
      const room = await prisma.rooms.findFirst({
        where: { id: room_id, camp_id },
      });

      if (!room) {
        throw new ApiError('NOT_FOUND', 'Room not found', 404);
      }
    }

    // Auto-routing: get category's default_team_id and find team lead
    let assigned_team_id = null;
    let assigned_user_id = null;
    let initial_status = 'open';

    if (category_id) {
      const category = await prisma.complaint_categories.findUnique({
        where: { id: category_id },
        select: { default_team_id: true },
      });

      if (category?.default_team_id) {
        assigned_team_id = category.default_team_id;

        // Find team lead
        const teamLead = await prisma.team_members.findFirst({
          where: {
            team_id: assigned_team_id,
            is_lead: true,
          },
          select: { user_id: true },
        });

        if (teamLead) {
          assigned_user_id = teamLead.user_id;
          initial_status = 'assigned';
        }
      }
    }

    // Create maintenance request (request_number auto-generated by trigger)
    const request = await prisma.maintenance_requests.create({
      data: {
        tenant_id: req.tenantId,
        camp_id,
        room_id,
        category_id,
        title,
        description,
        priority,
        status: initial_status,
        reported_by: req.user.id,
        reported_by_name,
        assigned_team_id,
        assigned_user_id,
        ...(assigned_user_id && { assigned_at: new Date() }),
        image_urls: image_urls || [],
      },
    });

    // Create notification for assigned user
    if (assigned_user_id) {
      await prisma.notifications.create({
        data: {
          tenant_id: req.tenantId,
          user_id: assigned_user_id,
          title: `New Maintenance Request: ${title}`,
          message: `You have been assigned to maintenance request ${request.request_number}`,
          type: 'maintenance_assigned',
          entity_type: 'maintenance_requests',
          entity_id: request.id,
        },
      });
    }

    // Audit log
    await prisma.audit_logs.create({
      data: {
        tenant_id: req.tenantId,
        user_id: req.user.id,
        action: 'maintenance.create',
        entity_type: 'maintenance_requests',
        entity_id: request.id,
        changes: {
          request_number: request.request_number,
          title,
          assigned_team_id,
          assigned_user_id,
        },
      },
    });

    logger.info({ user_id: req.user.id, request_id: request.id, request_number: request.request_number }, 'Maintenance request created');

    res.status(201).json({ request });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/maintenance
 * List maintenance requests with filters
 */
router.get('/', requirePermission('maintenance.read'), async (req, res, next) => {
  try {
    const { status, priority, team_id, room_id, camp_id, assigned_to_me } = req.query;

    const where = {
      tenant_id: req.tenantId,
      ...(status && { status }),
      ...(priority && { priority }),
      ...(team_id && { assigned_team_id: team_id }),
      ...(room_id && { room_id }),
      ...(camp_id && { camp_id }),
      ...(assigned_to_me === 'true' && { assigned_user_id: req.user.id }),
    };

    const requests = await prisma.maintenance_requests.findMany({
      where,
      orderBy: [
        { status: 'asc' },
        { priority: 'desc' },
        { created_at: 'desc' },
      ],
      include: {
        rooms: { select: { room_number: true } },
        camps: { select: { name: true } },
        teams: { select: { name: true } },
        users_maintenance_requests_assigned_user_idTousers: { select: { full_name: true } },
      },
    });

    res.json({ requests });
  } catch (error) {
    next(error);
  }
});

/**
 * GET /api/v1/maintenance/:id
 * Get single maintenance request with full details
 */
router.get('/:id', requirePermission('maintenance.read'), async (req, res, next) => {
  try {
    const { id } = req.params;

    const request = await prisma.maintenance_requests.findFirst({
      where: {
        id,
        tenant_id: req.tenantId,
      },
      include: {
        rooms: true,
        camps: true,
        complaint_categories: true,
        teams: {
          include: {
            team_members: {
              include: {
                users: { select: { id: true, full_name: true, email: true } },
              },
            },
          },
        },
        users_maintenance_requests_assigned_user_idTousers: {
          select: { id: true, full_name: true, email: true },
        },
        users_maintenance_requests_resolved_byTousers: {
          select: { id: true, full_name: true },
        },
      },
    });

    if (!request) {
      throw new ApiError('NOT_FOUND', 'Maintenance request not found', 404);
    }

    res.json({ request });
  } catch (error) {
    next(error);
  }
});

/**
 * PATCH /api/v1/maintenance/:id
 * Update maintenance request status/assignment
 */
router.patch('/:id', requirePermission('maintenance.write'), validate(updateMaintenanceSchema), async (req, res, next) => {
  try {
    const { id } = req.params;
    const { status, assigned_team_id, assigned_user_id, priority, resolution_notes } = req.body;

    // Get existing request
    const existing = await prisma.maintenance_requests.findFirst({
      where: {
        id,
        tenant_id: req.tenantId,
      },
    });

    if (!existing) {
      throw new ApiError('NOT_FOUND', 'Maintenance request not found', 404);
    }

    // Validate state transition if status is changing
    if (status && status !== existing.status) {
      if (!validateStateTransition(existing.status, status)) {
        throw new ApiError('INVALID_STATE', `Cannot transition from ${existing.status} to ${status}`, 422);
      }
    }

    const updates = {
      ...(priority && { priority }),
      ...(resolution_notes !== undefined && { resolution_notes }),
    };

    // Handle status changes
    if (status) {
      updates.status = status;

      // Auto-set started_at when moving to in_progress
      if (status === 'in_progress' && !existing.started_at) {
        updates.started_at = new Date();
      }

      // Auto-set resolved_at and resolved_by when moving to resolved
      if (status === 'resolved') {
        updates.resolved_at = new Date();
        updates.resolved_by = req.user.id;
      }
    }

    // Handle assignment changes
    if (assigned_team_id !== undefined || assigned_user_id !== undefined) {
      updates.assigned_team_id = assigned_team_id;
      updates.assigned_user_id = assigned_user_id;

      // If assigning and status is 'open', auto-change to 'assigned'
      if ((assigned_team_id || assigned_user_id) && existing.status === 'open') {
        updates.status = 'assigned';
        updates.assigned_at = new Date();
      }
    }

    const updated = await prisma.maintenance_requests.update({
      where: { id },
      data: updates,
    });

    logger.info({ user_id: req.user.id, request_id: id, updates }, 'Maintenance request updated');

    res.json({ request: updated });
  } catch (error) {
    next(error);
  }
});

export default router;
